### PR TITLE
fix to update speed and heading in unit stream

### LINKED ISSUE #82: Speed and heading not updated in unit stream
The speed and heading of units is not being updated in the units stream.

* Observed by watching LotATC and seeing a plane reverse course while the output stayed the same.
* Observed by comparing DCS-gRPC output to Tacview output and observing only the tacview headings change.

Proving it will require a huge dump of stats so to illustate the point I am going to put just a few entries demonstrating it.

(Altitude doesn't change in these three samples but I did observer changes in other units so altitude is fine, this is an AI unit in a racetrack which is why it is so steady)

```json
{
  "unit": {
    "id": 7013,
    "name": "RUSSIA air 13 unit1",
    "callsign": "106",
    "coalition": "COALITION_RED",
    "type": "C-101CC",
    "position": {
      "lat": 43.89192219804639,
      "lon": 40.93609502901023,
      "alt": 5486.39990234375
    },
    "groupName": "RUSSIA air 13",
    "numberInGroup": 1,
    "speed": 119.97181015273709,
    "heading": 126.50408556324253
  }
},
{
  "unit": {
    "id": 7013,
    "name": "RUSSIA air 13 unit1",
    "callsign": "106",
    "coalition": "COALITION_RED",
    "type": "C-101CC",
    "position": {
      "lat": 43.88827413932173,
      "lon": 40.94169167458405,
      "alt": 5486.39990234375
    },
    "groupName": "RUSSIA air 13",
    "numberInGroup": 1,
    "speed": 119.97181015273709,
    "heading": 126.50408556324253
  }
},
{
  "unit": {
    "id": 7013,
    "name": "RUSSIA air 13 unit1",
    "callsign": "106",
    "coalition": "COALITION_RED",
    "type": "C-101CC",
    "position": {
      "lat": 43.8702459604217,
      "lon": 40.969337211586804,
      "alt": 5486.39990234375
    },
    "groupName": "RUSSIA air 13",
    "numberInGroup": 1,
    "speed": 119.97181015273709,
    "heading": 126.50408556324253
  }
}
```

### PR DESCRIPTION
**Pull request by rkusa**
Update the unit stream to:
- don't look for player name changes anymore
- update a unit if speed and/or heading changed

Fixes #82

### CODE REVIEW

File: src/stream.rs [hunk 1]
```diff
@@ -253,36 +251,60 @@ impl UnitState {
...
-        let player_name = UnitService::get_player_name(
-            &ctx.rpc,
-            Request::new(unit::v0::GetPlayerNameRequest {
-                name: self.unit.name.clone(),
-            }),
-        )
-        .await?
-        .into_inner()
-        .player_name;
-        if player_name != self.unit.player_name {
```
Comment (rkusa) [inline src/stream.rs:283]: Not sure what my thoughts were, but I don't think the player name can change during the life-time of a unit, or can it? (thus removed and considered static)

Comment (rurounijones) [reply src/stream.rs:283]: I think you are correct here.

**Review by rurounijones — APPROVED** [review]
